---
name: go-build-test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: go-get-dependencies
        run: go get .
      - name: go-vet
        run: go get .
      - name: go-test
        run: go test
      - name: go-build
        run: go build -v ./...
      - name: ace-help
        run: ./ace -h
